src/objects/Consumer__c.object
<CustomObject>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Consumer</label>
    <nameField>
        <displayFormat>{0} - Member Since {YYYY}</displayFormat>
        <label>Consumer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Performance__c.object
<CustomObject>
    <fields>
        <fullName>Start_DateTime__c</fullName>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Alternative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rock</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Performances</relationshipLabel>
        <relationshipName>Performances</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Performance</label>
    <nameField>
        <label>Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Performances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Seat__c.object
<CustomObject>
    <fields>
        <fullName>Row__c</fullName>
        <label>Row</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seat_Number__c</fullName>
        <label>Seat Number</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <picklist>
            <picklistValues>
                <fullName>Orchestra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balcony</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Box Seat</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Seats</relationshipLabel>
        <relationshipName>Seats</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Seat</label>
    <nameField>
        <label>Seat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Consumer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consumer</label>
        <referenceTo>Consumer__c</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Performance__c</fullName>
        <description>DO NOT EDIT THIS FIELD AT ALL</description>
        <label>Performance</label>
        <referenceTo>Performance__c</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Seat__c</fullName>
        <description>DO NOT EDIT THIS FIELD AT ALL</description>
        <label>Seat</label>
        <referenceTo>Seat__c</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Reserved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refunded</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Venue__c.object
<CustomObject>
    <label>Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_ConsumerLifeTimeSpend.cls
/*
Test Class for the ConsumerLifeTimeSpend Trigger
*/
@isTest
private class Test_ConsumerLifeTimeSpend
	{
    static testMethod void ConsumerLifeTimeSpend()
    	{
		Profile up = [select Id from profile where name = '*UC-Ticket Sales Agent'];
  		User user = new User(alias = 'test', email='salesagent@uc.com',
			emailencodingkey='UTF-8', lastname='Sales Agent', languagelocalekey='en_US',
			localesidkey='en_US', profileid = up.Id, country='United States',
            timezonesidkey='America/Los_Angeles', username='salesagent@ucababana.com');
        insert user;	
    	
    	Consumer__c c = new Consumer__c();
    	c.Last_Name__c = 'Test Consumer';	
    	insert c;
    	
    	Venue__c v = new Venue__c();
    	v.Name = 'Arena Club';
    	insert v;
    	
    	Performance__c p = new Performance__c();
    	datetime startDatetime = Datetime.newInstance(2099, 20 , 12, 00, 00, 00);
    	p.Name = 'P1';
    	p.Start_DateTime__c = startDatetime;
    	p.Status__c = 'On Sale';
    	p.Type__c = 'Pop';
    	p.Venue__c = v.Id;
    	insert p;
    	
		list<Seat__c> Seats = new list<Seat__c>();
		for(Integer i=0; i<99; i++)
			{
			Seat__c s = new Seat__c();
			s.Name = 'Seat - '+i;
			s.Row__c = 'Row'+i;
			s.Section__c = 'Section';
			s.Seat_Number__c  = i;
			s.Venue__c = v.Id;
			Seats.add(s);
			}
		insert Seats;
		
		system.runas(user)
			{
			Test.startTest();
				{
				//Insert Tickets.	
				list<Ticket__c> Tickets = new list<Ticket__c>();
				for(Seat__c s: Seats)
					{
					Ticket__c t = new Ticket__c();
					t.Performance__c = p.Id;
					t.Seat__c = s.Id;
					t.Cost__c  = 200;
					t.Status__c = 'Purchased';
					t.Consumer__c = c.Id;
					Tickets.add(t);
					}
				insert Tickets;	
				
				//Update Tickets to reserved.
				for(Ticket__c t: Tickets)
					{
					t.Status__c	= 'Reserved';
					}
				update Tickets;
				
				//Delete all the Tickets.
				delete Tickets;	
				}
    		}
 		}
	}